# Welcome to Jekyll!
# This config file is meant for settings that affect your entire site, values which you are expected to set up once and rarely need to edit after that. For technical reasons, this file is *NOT* reloaded automatically when you use `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Dirty Robot Brew Works"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Dirty Robot Brew Works"
description              : "The web site of Dirty Robot Brew Works."
url                      : "https://dirtyro.bot"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "DirtyRobot/dirtyrobot.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/graphics/DirtyRobot.logo.white.horizontal.png"
masthead_title           : " " # overrides the website title displayed in the masthead, use " " for no title
copyright                : "Dirty Robot Brew Works"

remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum", "sunrise"
markdown                 : kramdown
locale                   : "en-US"
timezone                 : America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
permalink                : /:categories/:title/
paginate                 : 5 # amount of posts to show
paginate_path            : /page:num/
search                   : false

analytics:
  provider               : "google-gtag" # "google", "google-universal", "custom"
  google:
    tracking_id          : "G-2Q3WLEBJXN"
    anonymize_ip         : # true, false (default)

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name                   : "Dirty Robot"
  avatar                 : "/assets/graphics/DirtyRobot.icon.yellow.svg"
  bio                    : "A robotic nano-brewery."
  location               : "San Francisco"
  email                  : info@dirtyrobotbrewworks.com
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://dirtyro.bot"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/DirtyRobot"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "http://mastodon.social/@dirtyrobot"

footer:
  links:
    - label: ""
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@dirtyrobotbrewworks.com"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "http://github.com/DirtyRobot"
    - label: ""
      icon: "fab fa-fw fa-mastodon"
      url: "http://mastodon.social/@dirtyrobot"

collections:
  portfolio:
    output: true
    permalink: /:path

defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
